### ISSUE TITLE
WebUSB Connect button showing in Safari

### ISSUE THREAD

**Issue by duckida** [microbit-foundation/python-editor-next#368]
## Bug Description
The WebUSB "connect" button is showing in my Safari browser. When I click the button, it responds with a "Unfortunately, WebUSB is not supported in this browser..." message.

## How To Reproduce

1. Open the editor in Safari on Mac, or (untested) other non-Chromium browser.
2. Click on "connect" with the USB icon
3. See the error

## Expected behavior

Because I am using a browser that does not support WebUSB(Safari) I expect only the "download" button to show up, as it does in the current MakeCode and Python editors.
## Screenshots
https://photos.app.goo.gl/RT6fnH6crP6P38M56

(copy of images below added by @microbit-matt-hillsdon for convenience)

![image](https://user-images.githubusercontent.com/44397098/145781180-1e10c668-aa4e-4983-8ba0-78d09a724ca4.png)

## Environment

**Desktop:**
 - OS: macOS Monterey
 - Browser: Safari
 - Version: 15.1

**Comment by microbit-matt-hillsdon** [comment]
Thanks for your feedback @duckida.

For this new version of the editor, our current thinking is to make WebUSB more prominent (especially now it’s supported in Edge as well as Chrome). We’ve left the “Connect” action in so that Safari and Firefox users know it’s a possibility with another browser. Using WebUSB enables quicker flashing and use of the REPL. Of course, we still support Safari.

It’s also valuable for the look of the editor to be consistent across all browsers for people taking screenshots and putting them into books or materials (though of course, it's far to early in the development process for people to be doing that with this editor right now!).

I’m going to close this issue for now, as the behaviour is as designed, but we’ll keep this feedback in mind as we talk to more users about the alpha editor.
