### ISSUE TITLE
`display.show(value)` errors in editor but not on the micro:bit

### ISSUE THREAD

**Issue by microbit-mark** [microbit-foundation/python-editor-next#625]
Not sure if this is an editor or MicroPython bug, but this example will error in the editor

`display.show(Image.HEART, delay=500, clear=True)`

The error is probably expected behaviour as `Image.HEART` is not an iterable as per reference https://microbit-micropython.readthedocs.io/en/v2-docs/display.html?highlight=show#functions

However, when flashing this to the micro:bit the Heart image is displayed and the screen is cleared after a 500ms pause. This is confusing to users.

![image](https://user-images.githubusercontent.com/31242877/156171046-53e197fa-9535-4fd6-ae51-47b65e0fbd87.png)

**Comment by microbit-matt-hillsdon** [comment]
Closed by #681 

When we discussed this we observed that there was a nice simplification due to the incorrect override. We plan to discuss showing signatures with no optional parameters in the parameter help (as we currently do in Reference before "Show more"). There's a non-obvious UX issue to show to users that there are more parameters or a judgement call to decide it's not worth showing them to users so lots to talk about.
